### ISSUE TITLE
2 cosmetic but easy-to-fix bugs in virtualagc-master/VirtualAGC/Makefile

### ISSUE THREAD

**Issue by texadactyl** [virtualagc/virtualagc#1059]
Line 342: Conditionally strip files from list (skip the one PNG file by file extension).

Line 345: Add a -p option to -mkdir $@/Resources/source so that `mkdir` doesn't flag the existing directory as an error.

**Comment by rburkey2005** [comment]
Thanks, @texadactyl.  

I've swapped lines 341 and 342, so ApolloPatch2.png is only added to the directory _after_ the 'strip' commands are run.  I admit that the error message for it had been annoying me from time to time, but not enough to fix it.

As far as line 345 is concerned, I don't think the -p should be needed -- in fact, I don't think line 345 is needed at all ---  because one of the prerequisites to the rule for the temp/lVirtualAGC target is the temp/lVirtualAGC/Resources target, and one of the things building that target does is to create the temp/lVirtualAGC/Resources/Source directory anyway.  So the directory always exists by the time line 345 is reached.  But it's harmless to keep the line and to add -p to it, so in the interests of universal harmony and good will I've done so.  :smile:

**Comment by texadactyl** [comment]
On line 345, without the -p you get an error:

mkdir temp/lVirtualAGC/Resources/source
mkdir: cannot create directory ‘temp/lVirtualAGC/Resources/source’: File exists
Makefile:336: recipe for target 'temp/lVirtualAGC' failed
make[1]: [temp/lVirtualAGC] Error 1 (ignored)

Yes, it is an ignored error.  That's why I used the adjective "cosmetic".

**Comment by texadactyl** [comment]
Thanks for the quick response.
