### ISSUE TITLE
Schematic files with same name, different case

### ISSUE THREAD

**Issue by jimlawton** [virtualagc/virtualagc#1065]
1. In the directory `schematics/Schematics/2005100D` (https://github.com/virtualagc/virtualagc/tree/schematics/Schematics/2005100D), there are two files called `BOM.sch` and `bom.sch`. It's not clear which is correct.

2. In the directory `msSchematics/libs` (https://github.com/virtualagc/virtualagc/tree/schematics/msSchematics/libs), there are two files called `Device.lib` and `device.lib`.

I just noticed this when I tried to check out the `schematics` branch on a Mac where the default filesystem is case-insensitive.

**Comment by rburkey2005** [comment]
I deleted the wrong one.  It doesn't really matter, since you wouldn't normally open these .sch files directly, but would instead navigate down through the drawings starting from one of the .pro files ... in which case there's no way to get to the wrong file.  That's probably why I didn't notice it.  But it's best to get rid of it completely to avoid any more confusion than is absolutely necessary.  :-)  Thanks!

**Comment by rburkey2005** [comment]
Whoops!  I didn't notice the msSchematics/libs thing.

**Comment by jimlawton** [comment]
Yeah, sorry, I debated filing two separate issues, but ... lazy :-).

**Comment by rburkey2005** [comment]
I no longer know which of the libraries device.lib or Device.lib is "correct", because they were only used prior to forking Mike Stewart's repository, and neither of them is used any longer in this fork.  

Instead, the schematics for each of Mike's modules reside in separate folders, and each has its own individual library (MODULE-cache.lib or MODULE-rescue.lib, or both) within that folder which contains all of the component symbols needed by that specific schematic.  Those module-specific libraries are used by KiCad automatically without any setup.  That makes _all_ of the libraries in the libs/ folder extraneous, not just [Dd]evice.lib.  Since they don't cause any harm, I'd prefer not to delete them, though, given the difficulty I had getting any of Mike's stuff to work to begin with.  (I was using a different version of KiCad, and a lot of library stuff caused me problems.)

Also, none of the "official" schematics created from the MIT/IL drawings is in the msSchematics folder, so I'm not sure how much confusion an extra library or two in msSchematics can really cause, however poorly named.  All of the links from the website are into the Schematics/ folder.

That being the case, I'm just going to ignore the device.lib vs Device.lib issue.  It can be revisited later if it truly messes somebody up, but for now I'm going to call this "closed".

**Comment by rburkey2005** [comment]
Although, I suppose it could confuse somebody trying to make a local copy of the repository on Windows ....  Well, this may require more thought.

**Comment by jimlawton** [comment]
Ron, the problem with this is that multiple files differing only in case cause problems for case-insensitive filesystems. Mac OSX is a case in point. While it supports case-sensitive filesystems, the default for the root filesystem is case-insensitive. So if you check out the `schematics` branch on a Mac, you will most likely end up with a borked clone (always showing local mods), and the only way out is to `git checkout -f master`.

**Comment by rburkey2005** [comment]
I simply eliminated the entire libs/ directory.  The library files there aren't necessary for viewing the schematics in KiCad.  They would be useful if the schematics were being edited in order to add some symbol that was in those libraries but not already present on the schematics ... which seems unlikely.  Besides, the libs/ folder will always be in the history, so the individual libraries in it can always be retrieved by someone determined to do so.  I would have preferred not to do that, but trying to resolve the discrepancy between device.lib and Device.lib seemed much, much harder.

**Comment by rburkey2005** [comment]
I forgot to record [the appropriate place to look in the history, if anyone wanted to recover the libs/ folder](https://github.com/virtualagc/virtualagc/tree/d33ba6b78f70d055bc15fbbe9eb2db4b697dc92b/msSchematics/libs).
