### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by infinitymakerspace** [virtualagc/virtualagc#1126]
Hi guys, I have a query.  Is there a way to interact with virtual AGC via serial or other communication method.  Would like to play around by connecting Arduino or other development boards and SBC's to it .  Keep up the grate work

Warm regards from Port Elizabeth, South Africa

**Comment by rburkey2005** [comment]
@infinitymakerspace The AGC's CPU-emulation program is yaAGC, so I presume what you mean is that you'd like to run the original AGC software (such as LUMINARY or COLOSSUS) by means of yaAGC on (perhaps) a laptop computer, and then use a separate Arduino or similar to make peripheral devices for it.  There are several ways to do that, some easier than others.

As-is, yaAGC communicates to all peripheral devices using what I call a "virtual wire" system, which is implemented using networking.  How that works is described in some detail on [the website's "Develper Info" page](http://www.ibiblio.org/apollo/developer.html).  Thus if your SBC has a network stack, it's pretty easy communicate with yaAGC.  For an SBC like a Raspberry Pi 4, the board has enough oomph to simultaneously run both yaAGC _and_ the software you use to implement your peripheral device, so you can have something that's completely self-contained.  There's even [sample Python software provided for a Raspberry Pi 4](https://github.com/virtualagc/virtualagc/tree/master/piPeripheral) that emulates things like general purpose peripheral devices or DSKYs, which you can adapt to implement your own peripherals.  This is documented a little on [the website's "Do It Yourself" page](http://www.ibiblio.org/apollo/DIY.html#Your_Own_Peripheral_Devices).

If you are really determined to use a lower-end SBC without a network stack, you can still do it but it becomes somewhat harder.  What you have to do is to modify the yaAGC source code.  The source code has been somewhat modularized in a way that allows you to eliminate the "virtual wire" interface and replace it with an interface of your own devising.  Be warned that this has seldom been done, so I don't know what kinds of difficulties you may have run into, though I can tell you that this is the way the NASSP/Orbiter project implements the interface between yaAGC and the Orbiter spaceflight simulator, so it definitely can be done.  _Normally_, the source file SocketAPI.c in [the yaAGC source-code tree](https://github.com/virtualagc/virtualagc/tree/master/yaAGC) provides the interface.  There is, however, a replacement file called NullAPI.c that has all of necessary functions in it, but without any internal code so that the interface does nothing; you could therefore build your own customer interface between yaAGC and peripherals by fleshing out NullAPI.c to use a serial interface or whatever you wanted.

**Comment by infinitymakerspace** [comment]
Hi there

Great stuff thank you so much. I have been inspired Mike Stewart's work
with the AGC restoration and use of fpga etc.

Keep up the great work.

Regards
