### ISSUE TITLE
What does "xxBxx" notation mean?

### ISSUE THREAD

**Issue by jumpjack** [virtualagc/virtualagc#1156]
In AGC documents it's mentioned notation "xxBxx" for some visualizations in DSKY, but i don't understand if the "B" stands for "blinking" or if it's just a separator.

![immagine](https://user-images.githubusercontent.com/1620953/150804586-49612bf0-3676-40c5-95c1-1a53b34a11c1.png)

https://www.ibiblio.org/apollo/Documents/j2-80-E-2448-REV4_text.pdf

**Comment by thewonderidiot** [comment]
It means "blank" -- so that digit is not illuminated at all. These formats are also present in the [ASSEMBLY AND OPERATION INFORMATION](https://github.com/virtualagc/virtualagc/blob/master/Artemis072/ASSEMBLY_AND_OPERATION_INFORMATION.agc) section of the listing itself, which can be a bit more descriptive. [It also uses the XXBXX notation](https://github.com/virtualagc/virtualagc/blob/master/Artemis072/ASSEMBLY_AND_OPERATION_INFORMATION.agc#L392) for Noun 44. If you scroll down to [the "Registers and Scaling section"](https://github.com/virtualagc/virtualagc/blob/master/Artemis072/ASSEMBLY_AND_OPERATION_INFORMATION.agc#L584), you'll see that Noun 44, register 3 has format `L`.  And if you scroll down and find [format L](https://github.com/virtualagc/virtualagc/blob/master/Artemis072/ASSEMBLY_AND_OPERATION_INFORMATION.agc#L803), it has a complete description of what you'd expect to see in that register, including mentioning the blank. Hope this helps!
