### ISSUE TITLE
A really old AGC emulator dated 2001!

### ISSUE THREAD

**Issue by jumpjack** [virtualagc/virtualagc#1157]
Maybe you already knew this, anyway look at what I found: :-)

http://apollo.spaceborn.dk/dsky-sim.html

I copied it to github:

https://github.com/jumpjack/dskysim

**Comment by rburkey2005** [comment]
Yes, I'm aware of it.  The Virtual AGC website used to have a short description of it, but I guess I removed that a long time ago. 
 The only remaining reference to it I can find now is on the Virtual AGC website's change log from 2004.

Most likely the references to it disappeared because (if I recall correctly) it's not actually an AGC emulator.  Rather, you can enter verbs and nouns into it, and it displays stuff that the author (Ron Noteborn) thought it should display, but there's no actual model of an AGC behind that, nor any of the actual AGC software.  Sort of like something from a movie:  as long as it looks okay for the few seconds it might be on camera, it's good enough.  Or more accurately, as long as you don't enter anything Noteborn didn't expect into the DSKY, you'll be okay.  Not that there's anything wrong with that!  At the time it was created, it probably wouldn't have been possible to do any better than that with the materials available.  If the notes on Noteborn's website are correct, he wrote it in 2001, and I didn't even begin to think about an AGC emulator (or the AGC itself, for that matter) until 2003.

[Here](http://svtsim.com/moonjs/agc.html), on the other hand, is an actual online AGC+DSKY emulator, running actual AGC code.

At any rate, I don't see this as being issue for Virtual AGC, and am closing this out.
