### ISSUE TITLE
Failed to compile under Linux Mint with multiple instances of /bin/sh: 1: DGDBMI: not found

### ISSUE THREAD

**Issue by Xuser641** [virtualagc/virtualagc#1172]
Following instructions on the github page, I have installed all the required packages and have tried to build virtualagc with "make" but all I get is this:

matthew@LinuxMintVM:~/Documents/virtualagc-master$ cd yaAGC
matthew@LinuxMintVM:~/Documents/virtualagc-master/yaAGC$ make
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o main.o main.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: main.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o agc_cli.o agc_cli.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: agc_cli.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o agc_simulator.o agc_simulator.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: agc_simulator.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o agc_debugger.o agc_debugger.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: agc_debugger.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o agc_gdbmi.o agc_gdbmi.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: agc_gdbmi.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o agc_disassembler.o agc_disassembler.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: agc_disassembler.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o agc_help.o agc_help.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: agc_help.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o nbfgets.o nbfgets.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: nbfgets.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o agc_symtab.o agc_symtab.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: agc_symtab.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o NormalizeSourceName.o NormalizeSourceName.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: NormalizeSourceName.o] Error 127 (ignored)
DGDBMI -O0 -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o checkdec.o ../Tools/checkdec.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:242: checkdec.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o agc_engine_init.o agc_engine_init.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: agc_engine_init.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o agc_engine.o agc_engine.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: agc_engine.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o agc_utilities.o agc_utilities.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: agc_utilities.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o rfopen.o rfopen.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: rfopen.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o Backtrace.o Backtrace.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: Backtrace.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o SocketAPI.o SocketAPI.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: SocketAPI.o] Error 127 (ignored)
DGDBMI -DNVER= -DINSTALLDIR="\"/usr/local/bin\"" -c -o DecodeDigitalDownlink.o DecodeDigitalDownlink.c
/bin/sh: 1: DGDBMI: not found
make: [Makefile:248: DecodeDigitalDownlink.o] Error 127 (ignored)
ar -rc libyaAGC.a agc_engine_init.o agc_engine.o agc_utilities.o rfopen.o Backtrace.o SocketAPI.o DecodeDigitalDownlink.o
ar: agc_engine_init.o: No such file or directory
make: *** [Makefile:228: libyaAGC.a] Error 1
matthew@LinuxMintVM:~/Documents/virtualagc-master/yaAGC$ 

How do I fix this?

**Comment by ohommes** [comment]
You miss a "-" in front of: DGDBMI
It should be -DGDBMI

**Comment by rburkey2005** [comment]
@Xuser641  If you're referring to the section titled "Building the Virtual AGC software" that just contains the lines `cd yaAGC` / `make`, those instructions don't seem to be correct anyway.  The reason it's not correct is that (if it worked at all, which is doubtful), it would build the single program called "yaAGC" rather than the entire VirtualAGC suite.  If @ohommes says it would work for building just yaAGC, I'll accept that it might.

The very next section, titled "Linux" says instead "to build, simply `cd` into the directory containing the source and do: `make`".  That's referring to the parent directory of yaAGC/, namely to your virtualagc-master/ directory.  That's much closer to reality.

However ... it appears to me that the instructions on github are generally out-of-date with respect to [the Virtual AGC website's instructions](http://www.ibiblio.org/apollo/download.html#Linux_), which are fully up-to-date.  I'd recommend using the website's instructions instead, as they are maintained much better.

**Comment by Xuser641** [comment]
After following the websites instructions, it appears to have built but I cannot find where it put the executable to run the program.

**Comment by rburkey2005** [comment]
Here's what the instructions on the website say about that:

> On supported Linux variants, the build process creates a desktop icon from which you can run Virtual AGC.  In some versions of Linux, you will need to right-click the icon and indicate that it is "trusted" before it will work properly. You can "uninstall" by removing the icon, the ~/VirtualAGC folder, and the source-code directory you downloaded from GitHub.

>On unsupported Linux variants, there may be no desktop icon, and you may need to run the program from a command line, as follows:
>`cd ~/VirtualAGC/Resources`
>`../bin/VirtualAGC`

In other words, it put it into a new folder called ~/VirtualAGC/.  On Linux Mint, you should now find a desktop icon.  If not, you can enter the command-line commands mentioned above. 

This assumes that you actually used the `make install` command recommended by the website, as opposed to something like just `make` by itself.  If you didn't do `make install` (so that you didn't really "install" it), but it still built, then the stuff will just be left where it was built.  If I understand your directory setup properly, you should be able to do the following:

`cd ~/Documents/virtualagc-master/VirtualAGC/temp/lVirtualAGC/Resources`
`../bin/VirtualAGC`

**Comment by Xuser641** [comment]
There is a new VirtualAGC folder but there is no "temp" or "Resources" folder inside of it. I wonder if the "make install" command is not completing correctly. =

**Comment by rburkey2005** [comment]
Just to clarify, you'd expect to have Resources/ and bin/ in ~/VirtualAGC/.  You'd have temp/ under your ~/Documents/virtualagc-master/VirtualAGC/ folder.  The latter is the build directory, and the former is the installation directory. 
 Which, of course, is not your issue.

I'd suggest that you capture a record of the entire build by doing

`make install &>log.txt`

(or whatever filename you prefer) and posting the file or a cut-and-paste of its contents here.

But I don't actually see any possible way ~/VirtualAGC/ could be created and still be empty, because it isn't created until after the entire build has completed, and the very next thing that happens is that the entire contents of the build is copied into it.

**Comment by rburkey2005** [comment]
For example, my own clone of the github repository is in my local directory ~/git/virtualagc.  To build a perfectly clean version of VirtualAGC, I might do something like this:

```
rm ~/VirtualAGC -rf
cd ~/git/virtualagc
make clean install
```
Removing ~/VirtualAGC isn't necessary, of course, but this will make sure that if it exists afterward, it's because the build procedure created it, rather than just lingering from some failed attempt in the past.  The messages I receive during the build look like this:

```
for subdir in Validation Zerlina56 Luminary131 Colossus249 Comanche055  Luminary099 Artemis072 Colossus237 Luminary130 Aurora12 Sunburst120 Luminary210 Retread44 Luminary069 SuperJob Luminary116 Borealis Sunburst37 LMY99R0 Retread50 SundialE LUM69R2 Luminary097 Luminary098 Comanche051 Artemis071 Luminary178 Luminary163 Luminary173 SundanceXXX Sundance306ish Comanche044 Comanche045 Manche45R2 Luminary096 Solarium055 TRIVIUM TRIVIUM-repaired ; do make PREFIX=/usr/local NVER=\\\"2020-12-24\\\" CFLAGS="-Wall -Werror -DALLOW_BSUB -g -O0" CURSES="-lcurses" LIBS2=" " NOREADLINE=yes ReadlineForWin32=  EXT= -C $subdir clean ; done
make[1]: Entering directory '/home/rburkey/git/virtualagc/Validation'

[snip]

# Create installation directory.
mkdir ~/VirtualAGC
mkdir: cannot create directory ‘/home/rburkey/VirtualAGC’: File exists
make: [Makefile:768: install] Error 1 (ignored)
cp -a VirtualAGC/temp/lVirtualAGC/* ~/VirtualAGC
chmod +x temp.virtualagc
mv temp.virtualagc $HOME/Desktop/VirtualAGC.desktop

================================================================
Run Virtual AGC from its desktop icon.
Or else, run Virtual AGC from a command-line as follows:
  cd ~/VirtualAGC/Resources
  ../bin/VirtualAGC
================================================================
```
If I then do 
`ls -l ~/VirtualAGC`

I see

```
total 16
drwxr-xr-x 2 rburkey rburkey  4096 Jun 30 17:46 bin
drwxr-xr-x 8 rburkey rburkey 12288 Jun 30 17:46 Resources
```

**Comment by Xuser641** [comment]
Ok. Here is a the log of the "make" process.
[log.txt](https://github.com/virtualagc/virtualagc/files/9077559/log.txt)

**Comment by rburkey2005** [comment]
@Xuser641 That's freakish.  It's the same problem now being reported as issue #1173, except that that's in Mac OS X rather than Linux.  So at least I know what to say about it, even if I don't immediately know how to fix it.  :smile:

The error message indicates that it can't find the Python 2 interpreter, which is necessary to run the check_buggers.py script, and hence the build fails.  The check_buggers.py script correctly begins with the line "`#!/usr/bin/env python`", which should find the Python 2 interpreter if it's installed.

If at a command line you type

`/usr/bin/env python`

does it in fact run Python 2.7.x?  If Python 2 isn't installed, you'll need to install it.

**Comment by Xuser641** [comment]
It did not find python, so I installed python and it built and I was able to run it.

**Comment by rburkey2005** [comment]
:+1: I had already modified the build instructions on the website a few days ago to indicate that some users might need to do that, so hopefully it won't catch anyone else.
