### ISSUE TITLE
Transcribe THROTTLE CONTROL (pp. 849-858)

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#227]
Transcribe the scans for the THROTTLE CONTROL log section into [its source file](https://github.com/rburkey2005/virtualagc/blob/master/Sunburst120/THROTTLE_CONTROL.agc). This section ranges from pages 849 to 858.

This section has [a corresponding log section in Luminary 099](https://github.com/rburkey2005/virtualagc/blob/master/Luminary099/THROTTLE_CONTROL_ROUTINES.agc), though it has a slightly different name. The two are probably somewhat similar. I recommend starting from that, and looking for any changes in the Sunburst scans.

Reduced quality scans can be found [here](http://www.ibiblio.org/apollo/ScansForConversion/Sunburst120/). The original quality scans are available at [the Internet Archive page for BURST120](https://archive.org/details/yulsystemforagcr00nasa). Note that in both cases, the page numbers specified on this ticket are those printed on the original pages, not those in the filenames. The numbers will be close, though, so you should be able to find them pretty quickly. The start of the log section should be fairly obvious.

**Comment by thewonderidiot** [comment]
@rburkey2005, is there a precedent for the □ characters used in this section (like at the bottom of http://www.ibiblio.org/apollo/ScansForConversion/Sunburst120/Sunburst120-0850.jpg)?

**Comment by rburkey2005** [comment]
I don't recall seeing them specifically before.  However, you've undoubtedly seen a number of odd character usages, like ":" in places of quotes or "-" in place of ":", and noticed that these substitutions aren't always the same in all places.  My assumption has always been that either the printers or some other i/o device (like the card punches or card readers) didn't always support what we would think of as a full character set, so that sometimes there were either deliberate or inadvertant substitutions for various punctuation characters, and that furthermore these might have changed over the course of time as equipment or personnel changed.

Of course, that's only an assumption.

If I encountered such a thing, I'd probably substitute it with something like "#===========..." without giving it a second thought.

**Comment by thewonderidiot** [comment]
= is what I was thinking too. Thanks!
