### ISSUE TITLE
Transcribe the octal listing.

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#443]
Checksums hadn't yet been invented for the AGC when Retread was made, so there's no checksum words. There's also gaps between the words. Also, the printer sucks so some digits are printed so far off as to be almost not present at all. Fun times!

Here are octal pages prepared with octopus: [retread_prepared.zip](https://github.com/virtualagc/virtualagc/files/653749/retread_prepared.zip)

**Comment by rburkey2005** [comment]
@thewonderidiot I'm afraid OmniPage isn't going to work on this.  I tried both the B&W cropped pages you prepared, and the manually-cropped original JP2's.  The problem is that while the character recognition isn't bad, due to the Snaggletoothing and skewed pages, OmniPage is awful at creating the zones (which are like bounding boxes, but for words rather than characters), so the stuff comes out all rearranged.  By that, I mean that many of octals are transposed between adjacent lines.  And the paragraphs tend to have 5-7 lines in them rather than 4, with empty spaces. Rearranging the octals is more time-consuming, I think, than manual data-entry would be, and a lot more tiring. At any rate, I don't want to do it.

On the good side, Tessaract is able to create bounding-boxes for the characters quite well, so Proofer.py can probably be made to work, with some effort to account for Snaggletoothing.  I wonder if you could possibly do a Tesseract run on them (using the old training data for, I guess, Sunburst)?  I don't want to have to do manual data-entry if Tesseract might be able to produce reasonable results.  Since we have Proofer.py, it doesn't have to be as accurate up-front as it did before, so we may not have to spend any effort training Tesseract.

In the meantime, I'll look into seeing if deskewing the pages helps any.

**Comment by thewonderidiot** [comment]
There's another option we could try that would get omnipage to work, although it's not clear if it would be more or less effort. Since tesseract is making good boxes, we _could_ try writing a script to vertically reposition all of the characters on a line to the average position.

But yeah, I'll do a pass with Tesseract. I might also manually edit 00000 1 in to all of holes just to make the blocks all solid.

**Comment by thewonderidiot** [comment]
I'm about to start in on the tesseract pass, but in the mean time here's my "cleaned up" octal images: 
[retread_prepared2.zip](https://github.com/virtualagc/virtualagc/files/656387/retread_prepared2.zip)

In these, I've removed most (all?) junk, inserted 00000 1 into all gaps, and also pulled apart many characters that were vertically close enough to bleed together.

**Comment by thewonderidiot** [comment]
@rburkey2005, I've filled in the binsource with tesseract-generated data. Both Sunburst and stock English trainings were disastrous, so I used ProoferBox to build a training set specifically for Retread based on the first four pages. I then regenerated using that one, and proofed the first bank, and only found a (comparatively very) small number of errors per page. There were only a dozen or so parity errors throughout, which is hopefully a good sign.

I've also, in the process, further edited the prepared images to vertically separate more characters and remove more junk. The latest set of images is here: 
[retread_prepared2.zip](https://github.com/virtualagc/virtualagc/files/656616/retread_prepared2.zip)

**Comment by rburkey2005** [comment]
@thewonderidiot Proofing/correction with ProoferBox.py went smooth as silk, pretty much.  There were some errors, admittedly, but not huge numbers of them.

I'm going to close this issue, but the fact that there are no checksums makes me less confident of correctness than I'd normally be.  Of course, we could just wait for the source to be available and then perform a cross-check, but one could also argue for having an independent proofing pass (i.e., independently of _me_) on the binsource.  Whether or not we want to do that, I've prepared for it by making all of the proofing imagery available [on the main website](http://www.ibiblio.org/apollo/Downloads/proofingRetread44.zip).   I haven't written up anything about how to use it, but if we do create a second issue for an independent proofing pass, I'll add an explanation in the comments there.

**Comment by thewonderidiot** [comment]
Excellent! I had been thinking the same about a dual proofing, so I can do that. I also want to cross-check the sketchier digits against the octals printed next to the instructions anyways, to make sure that in all cases where I had to crop out a random half-digit that I selected the right half-digit to remove.

**Comment by thewonderidiot** [comment]
So I don't currently have access to my FPGA, but I did boot up Retread on VirtualAGC and poke around at it. V35 unexpectedly lit _all_ the lights, including the spares, which is kind of neat. I also kicked off an instruction test and interestingly, we seem to be failing one of the instruction checks (DCA of an SC register) at 07,2545. And even more interestingly, after this happens, PINBALL stops responding to me whatsoever (I had to get the address of the failure by rebooting VirtualAGC and then examining memory location 1044)... but I don't see anything in the code that seems like it should cause that.

It's possible that this is just being caused by a bad octal somewhere, of course.

**Comment by rburkey2005** [comment]
Yes, I didn't actually check against the octals embedded in the source, and that's mostly what I was concerned about. I didn't do it personally, because I checked the unusual cases against the pure archive.org pages, and I could always tell (I rationalized) what the digit had been. 

It's clear that the physical printer had the characters on a wheel or something similar, because the "extra" parts you wiped away were always from an adjacent digit:  0-1, 1-2, 2-3, etc.  So, for example, if you are worried whether the digit is the bottom of a 6 or a 0, but there's the top of a 7 below it, that tells you it was a 6.  And the worst cases were always in one particular column in the second set of octals from the left, so I presume the printer must have had multiple wheels, and just one of them must have had worse alignment than the others.  Or something along those lines, anyway, if that's not the precise physical mechanism.  But I suppose it's possible also that in cases where I chose the bottom of one character, perhaps I should have been choosing the top of the other one!  So in the example above, maybe it wasn't a 6 or a 0, but rather a 7, and the alignment of the wheel was just really, really poorer than I supposed.

And it's also possible just to miss stuff in ProoferBox's imagery.  I always look through them twice, and I usually find something on the second pass that I didn't notice on the first one.  But that's a losing battle after a while.

**Comment by thewonderidiot** [comment]
Well, good news (?). The hardware sim fails in exactly the same way, at exactly the same address. So it's very likely not an emulation error unless I somehow independently wired in the same error.

I did find a way to recover -- if you hit ENTER again to re-execute V21N27, then press 0 then ENTER, it recovers. The computer is just in a very, very tight failure loop, which by the time of Aurora would have triggered a WHIMPER and subsequent reset.

**Comment by thewonderidiot** [comment]
Okay, I did another pass and found/fixed three errors. We still fail at the same place in the instruction check, so there may still be something hiding from us.

**Comment by rburkey2005** [comment]
And those 3 errors, particularly the 3rd, are all totally obvious from the printout, too, without even having to look at the embedded octals.  Embarassing ... but not surprising.  I'll make another pass myself.

**Comment by rburkey2005** [comment]
In all the preceding passes, the vast majority of errors (in the following schema) were in the Y position:

  oooooo XYoooo oooooo ... oooooo

I've visually checked the XY positions against the scanned images as intensively as I know how, and have found one more error (in Y).

**Comment by thewonderidiot** [comment]
Still no dice on the instruction check. I've been studying it this morning and think we may have found an actual honest-to-goodness instruction implementation difference in Block II.

The failing routine in question is here -- look for "CHECKS DCA OF AN SC REGISTER": https://archive.org/stream/blkiiretreadprog00sher#page/219/mode/1up

It puts -2 into Q and +1 into L, then performs a DCA L. It then adds together A and L, and checks the result is -1. That seems to imply that its assuming that the DCA L will make c(A) = -2 and c(L) +1... but, as according to the VirtualAGC language manual, "The instruction "DCA L" is an unusual case.   Since the less-significant word is processed first and then the more-significant word, the effect will be to first load the L register with the contents of the Q register, and then to load the A register with the contents of L.  In other words, A and L will both be loaded with the contents of the 16-bit register Q."

As far as I can tell looking at the hardware sim and cross-checking the pulses against AGC4 Memo 9, your description of what should happen is accurate. I'll keep looking for any way in which L might not get clobbered during the first MCT... but this might end up being a question for Hugh.

**Comment by thewonderidiot** [comment]
Here's the waveform view of the DCA0 and DCA1 sequences of the DCA L in this test:
![dca](https://cloud.githubusercontent.com/assets/94056/21289115/59716264-c449-11e6-8cb7-d08af003cde1.png)

**Comment by rburkey2005** [comment]
You'd suppose that by version 44 of anything, the basic self-test would be working.  On the other hand, if this is what corresponds to D--SC in Aurora, it certainly looks different, but I'm too loopy from correcting Lum 99 to wade through it right now.

**Comment by thewonderidiot** [comment]
Yeah, D--SC is the corresponding test in Aurora. Here's that test, further annotated by me to show register values at each step:
```
                             #  D--SC CHECKS DCS SC, DXCH SC, AND DCA SC.
D--SC    CA       S+2                                   
         TS       L          #  +2
         CA       S+1                                   
         EXTEND                                         
         DCS      A          #  $ DCS SC, C(L) = -2
         TC       -1CHK                                 
                             #  AFTER DXCH C(A) = B(Q) = +3, C(L) = B(A) = +0, C(Q) = B(L) = -1. ## (actually -2)
         DXCH     L          #  $ DXCH SC
         TS       SKEEP3     ## SKEEP3 = +3
         AD       Q          ## c(A) = +3 + (-2) = +1
         TC       +1CHK                                 
         CA       L          ## c(A) = c(L) = +0                           
         TC       +0CHK                                 
         CA       S-1        ## c(A) = -1                           
         TS       Q          ## c(Q) = -1                           
         CS       A          ## c(A) = +1                           
         EXTEND              ## Before DCA L, C(A) = +1, C(L) = +0, C(Q) = -1.                           
                             #  AFTER DCA C(A) = C(L) = C(Q) = B(Q) = -1.
         DCA      L          #  $ DCA SC
         AD       Q          ## c(A) =  -1 + -1 = -2                          
         AD       SKEEP3     ## c(A) = -2 + 3 = +1                           
         TC       +1CHK                                 
         CA       L          ## c(A) = -1                           
         TC       -1CHK       
```

So it seems to agree with us, and disagree with Retread's check.

**Comment by rburkey2005** [comment]
The dates on the Block II schematics are hard to read, but at least [this one](http://www.ibiblio.org/apollo/klabs/history/agc_schematics_block2/logic/5011-1.jpg) clearly says August 1965.  Were there even Block II AGCs in July 1965?  Maybe they were getting a jump on writing Block II software before Block II computers existed.

**Comment by rburkey2005** [comment]
I hate to fall back on Wikipedia :smile:, but it says the Block II AGC was designed in 1966.

**Comment by thewonderidiot** [comment]
Yeah... I'm highly skeptical of most AGC-related stuff on Wikipedia, to be honest. Here's a quote from R-700 volume 3:

> Program planning in the early part of 1963 indicates the second production system, which included AGC7, was to be flown in the Spring of 1965. Also, in the planning for Block II, during the Spring of 1965, the production prototypes were scheduled to start in August 1965 and to be followed by the flight hardware in December 1965. As a result the design efforts and evaluations of both Block I and Block II overlapped. If block changes in design were planned for initially, the change process may have operated more smoothly.

And here's a table listing milestones of the hardware development:
![agc_milestones](https://cloud.githubusercontent.com/assets/94056/21289904/a77dd7da-c45d-11e6-9eaa-dc8f36aefc2c.png)

July 1965 saw the initial design release for the Block II. There was another "flight configuration" design release in February of 1966, still well before our version of Aurora. Hugh has indicated in the past that he didn't think any instruction changes were a part of that re-release, though.

As for what physically existed then -- the production prototype didn't show up until November '65, but I imagine that the rack-mounted test/development version existed in that period. And this release of Retread was to Raytheon to be built into physical modules. Here's the table on the page preceding the flight module version page:
![assemblies](https://cloud.githubusercontent.com/assets/94056/21289931/4df4314a-c45e-11e6-84fe-cfbff2060537.png)

It goes into less detail, but has enough. Retread 44 was used for the "Computer Test BI. II Prototype", and morphed into a LM system test by revision 50 (which then presumably evolved into Aurora). So they did make rope modules for it, and did use them on _something_ at least.

The Computer History Museum, by the way, has Retread 50 modules in it. I now really want to dump them. Maybe some day, in some perfect world, we can hook them up with Francois. :)

**Comment by rburkey2005** [comment]
I understand what you're trying to say, but in the end the time-windows you're describing are narrow enough only enough to say that they may or may not have been able to work with final Block II hardware in that time frame.  It certainly doesn't demonstrate that they had enough experience with it to have fully debugged Retread 44 using it.  I think.  If Retread 44 had worked perfectly for us, it would push the conclusion towards saying that they had indeed done so; but since it didn't, I think it leaves enough room for doubt that they did not.  I'm going to ask both Hugh and Don and cc you on it.

**Comment by thewonderidiot** [comment]
Haha, sure, that's all I was really trying to say -- that it was run on some iteration of the Block II hardware at some point, and it's possible that at one point it did manage to pass but no longer did on the flight configuration. :smile:

**Comment by rburkey2005** [comment]
Oops, I thought we were each using equally-shaky arguments to come to opposite conclusions.  :smile:

**Comment by rburkey2005** [comment]
For anybody who might read this (other than @thewonderidiot, who was cc'd on the emails :smile:), Hugh Blair-Smith says, in his own words, that the Retread code in question is "wrong wrong wrong".  He speculates that it was written prior to the hardware being available, and that the simulator writers (not us, the original ones) might simply have been confused about the operation of the DCA instruction.  In other words, he more-or-less endorses the speculations above, but _not_ that it's some particular characteristic of the BLK2 assembler target.

**Comment by thewonderidiot** [comment]
Based on what I'm seeing with bdiffhead, all remaining binary differences are due to yaYUL, so I'm pretty sure we've got the octals all right. I didn't find any more octal errors while fixing things.
