### ISSUE TITLE
Correct code errors in the completed transcription.

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#558]
Probably going to need yaYUL changes to handle LOC +n and no banksums.

**Comment by thewonderidiot** [comment]
I've added the LOC alias for SETLOC and added support for relative SETLOCs and LOCs. I also had to weaken the EXTEND sanity checking, because AGC BLK2 INSTRUCTION CHECK uses a "TC 0006" with an INDEX to turn it into a "TC 0002", meaning it should not necessarily be treated as an EXTEND. I've done this by only erroring out for _explicit_ EXTENDs; now TC 6 may or may not be followed by an extracode instruction.

There's now two remaining yaYUL behaviors causing binary differences. First is the banksums as mentioned above. The second is quite interesting:

<img width="275" alt="screen shot 2016-12-18 at 5 21 18 pm" src="https://cloud.githubusercontent.com/assets/94056/21298461/7c7650fa-c546-11e6-89c1-0b220fa98c6f.png">

The instruction "2 0002" actually gets assembled to _20003_, presumably because the 2 when used with an erasable address corresponds to *DAS*, which has its argument incremented by one when assembled.

**Comment by rburkey2005** [comment]
Unfortunately, there are some things in yaYUL that I don't really understand, and simply had to do it a certain way to match what was happening in the actual listings, without having any particular rationale for it.  The behavior of stuff like this "2 0002" thing is likely one of them; I don't actually recall the details, but seem to recall it giving me fits.  So fixing stuff like it is tricky, since it's likely to break something else if not done just so.  Of course, now that we actually have YUL, I suppose we could find out what is _really_ supposed to be happening.  Or &mdash; and I may have done this sometimes in the early days &mdash; it's possible to just replace it with OCT 20003, add a ## note to that effect, and forget about it.  If there's only one or two instances, I might vote for that alternative.

@jimlawton Do you remember seeing in YUL (or perhaps just know) how "instructions" like this are supposed to be handled?

**Comment by rburkey2005** [comment]
The thing about the 2=DAS explanation is that the only reason I'd see for coding it like this is if the NDX was going to modify the instruction type.  If it was just going to modify the operand, why not just say DAS instead of 2?  And if it's not going to be a DAS after the NDX affects it, why treat the operand in a DAS-specific way?  Unless, I suppose, it was simply coded before YUL supported the DAS instruction, and so they _had_ to say 2 to get it to assemble.

**Comment by thewonderidiot** [comment]
Nah, there's other DAS's in the immediate vicinity. I agree that it's super weird -- that's just the only explanation I can reasonably come up with. Perhaps YUL treated mnemonics and their opcode numbers the same way... it then wouldn't have any means to know (without some sort of static analysis pass) whether a preceding INDEX was going to change the opcode or not. I found the place where numeric opcodes are handled, and am going to try putting in special cases for DAS, DCA, DCS, DXCH, just to see if anything else breaks.

This is, by the way, the only instance of this in Retread. So far though Retread has 0 workarounds, so  it'd be pretty swell to keep it that way. :)

**Comment by thewonderidiot** [comment]
Well, I implemented what I was talking about above -- basically, resolving the operand for numeric instructions to determine the quarter code, and adding 1 in cases of DXCH, DAS, DCA, and DCS. Nothing broke, so I think this one word must be the first and only case of this.

I also added a --no-checksums to yaYUL, similar to oct2bin, to prevent it from automatically generating banksums. With these two changes, the assembly and binsource are identical. :smile:

**Comment by thewonderidiot** [comment]
Patching the incorrect DCA L test is leading to interesting results. Both yaAGC and the hardware sim are failing... but on different tests. yaAGC is failing in the division tests (dangit I thought we got all of those), and the hardware sim is failing on some test looking at the interaction between the MASK instruction and overflow. Harumph!

**Comment by rburkey2005** [comment]
Great, thanks for yaYUL fixes!  

Not so great about the test failures, but it's great we have Retread to perform the breakage for us.  Since the software and hardware sims are failing differently, we can't exactly explain away more than one of the breakages as pre-working-hardware code, but _one_ of them could be.

I assume that it's possible that other tests downstream from these also fail, but that we won't know until these are fixed.  At least with the software sim, it should be possible with the debugger to bypass failed tests, and thus get a complete list of all tests that fail, without necessarily having to fix them.  Not that I'm proposing it, since I don't personally intend to stop what I'm doing and work on that instead, nor do I know what value such a list would have, but at least it's a theoretical possibility.
