### ISSUE TITLE
Correct comments in the completed transcription.

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#560]
Hopefully some form of octopus/ProoferComments will work well enough with snaggleprinter. This was based off of the already comment-proofed Aurora 12, so I anticipate there being much fewer errors in this than we've been seeing so far.

**Comment by rburkey2005** [comment]
Probably.  Also, I feel much better after seeing the results on Retread's octals.  There were also changes made to ProoferComments whilst working on Luminary 99 that should aid in addressing the snaggliness when the time comes, though they relate more to skew than snaggle.  However, I intend to complete Comanche 55 and Luminary 210, both of which have had work done on them already, before proceeding with this one.

**Comment by rburkey2005** [comment]
I took a little break from proofing Luminary 210 (which is essentially complete but needs one final once-over, so it's not yet committed) to proof Retread.  Since the starting point (for our effort) of Retread 44 was Aurora 12, which had already been proofed, I thought it might be interesting to look at a few statistics about that. 

While I don't normally keep track of the total number of comment fixes, for a rule of thumb let's say that typically I might find an average of 5 errors per page, so in Retread 44's 240 pages I might have expected to find 1000-1500 comment-text errors.  In actuality I found 29 errors.

Of those 29 errors found in Retread 44, 6 derived from errors lingering in Aurora 12, and I back-ported those fixes into Aurora 12.  The remaining 23 errors were all-new.

**Comment by thewonderidiot** [comment]
Not too shabby. That bodes well for future transcriptions based on comment-proofed programs. :smile:

**Comment by rburkey2005** [comment]
Sure ... All we need now is lots more AGC versions to transcribe!

**Comment by indy91** [comment]
Sundance, Sundisk, Skylark... what are we waiting for? :smiley:
