### ISSUE TITLE
Understand/correct errors identified by Retread 44's instruction check

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#562]
Retread's instruction check doesn't pass on either yaAGC or my hardware sim. Some of this can be pinned on Retread 44 having been mostly written before hardware was available to run it on; however, there is a chance that some failures are the result of emulation and/or wiring errors. This ticket is to track analysis of the failures and their resolutions, if any.

The procedure for running the instruction test is as follows:
1. Boot Retread in yaAGC or the hardware sim
2. Start the tests with V21N27E  1E
3. Upon program alarm, enter  E  0E  (re-executing the VN and replacing the 1 with a 0)
4. View the address (+1 and sans bank) of the failure with V01N01E  1044E

Failing tests are as follows:

Test | Address | Fails On | Explanation
----|--------|--------|----------
DCA of SC Register | 07,2544 | Both     | Retread code is incorrect; see #443 for more details.
DV6-+ | 10,2300 | yaAGC | Emulation error in DV; this has now been fixed
WANDUF | 10,2535 | Both | Retread code is incorrect; interrupts not inhibited while dealing with overflow in Q.

**Comment by thewonderidiot** [comment]
So, the WANDUF failure is not the only I/O instruction overflow test that fails. However, these failures are totally random.

It appears that the tests rely on the Q register holding overflow, but don't inhibit interrupts during their execution. Therefore, a poorly timed interrupt might destroy the overflow condition in Q, causing the test to fail.

Wrapping all of these tests in INHINT...RELINT makes all of them consistently pass.

**Comment by thewonderidiot** [comment]
The DV failure was an actual bug in yaAGC. In the case where A == divisor and |L| == 0, the value calculated for the L register was not being sign-extended. L's automatic overflow correction was then clobbering the sign of that value. Aurora seems to have only tested the positive case of this, in which the 0 sign would have been harmlessly clobbered by 0, not changing the sign.

**Comment by rburkey2005** [comment]
Good old Retread! Thanks for taking care of that, as always!

**Comment by thewonderidiot** [comment]
Certainly! :) I suspect that this is the last of the issues -- yaAGC can run all of the tests for a few hours now without issues. And the time-to-failure on the hardware sim didn't seem particularly consistent last night so there's a good chance the INHINT/RELINT fix for the I/O tests will make everything sail smoothly there as well.

But yeah, good old Retread. Buggy though they may be, more tests are always good. :smile:

**Comment by rburkey2005** [comment]
Since we're unlikely to get any additional AGC software that would do the tests differently, at some point it might be worthwhile to figure out how to do the following (in an automated way):

1. Generate a random set of instructions.
2. Run it on _both_ the software hardware sims for X number of instruction cycles, capturing the contents of a central-register set after each instruction.
3. Diff the captures from the software and hardware sims to find discrepancies.
4. Go back to step 1.

This wouldn't tell us that the execution was correct, but might find additional differences between the software and hardware sims.  Interrupts would be the rub, since they presumably couldn't be synchronized between the hardware and software sims, so perhaps it would have to be done with interrupts (and perhaps the night watchman) completely disabled somehow.

That's basically the way I debugged the Block I simulator, by doing a cycle-by-cycle comparison against John Pultorak's Block I simulator ... though not using randomized code sequences.  Usually John was right and I was wrong, but not always.

**Comment by thewonderidiot** [comment]
That's a good idea, and hopefully shouldn't be _too_ hard. The code I'm using to disassemble the instruction and display it on the waveform viewer is probably a good starting place. And yeah, all of the various hardware alarms would have to be inhibited for it. 

There's a lot of tests that still need to be written, too, for features that don't explicitly have tests for them. Like the hardware alarms and some interrupt behaviors (I think yaAGC by default still doesn't allow the swapping-out of the instruction returned to from an interrupt).

My end goal is to have yaAGC be indistinguishable from the actual hardware from the program's point of view. I'm not sure that will every be completely possible, though... we'll have to see. But for example, one way to detect whether or not you're in yaAGC right now is to write a value to a fictitious I/O channel and then try to read it back in. In the hardware, you'll get zero, but I believe yaAGC will give you back the value you wrote out.

**Comment by thewonderidiot** [comment]
Sort of along these lines... I've been playing around with the idea of "forking" Aurora and expanding the capabilities there. Probably after removing all of the DAP stuff added by the DAP group. There's a bit more test infrastructure there that would be useful... and it would give us access to all of PINBALL's capabilities. But we could, for example, pull over the instruction checks from Retread, plus fixes, and all of the custom stuff from Validation, and just have one big test rope that contains all the tests, both ours and the original developers'.

**Comment by rburkey2005** [comment]
I was writing up a response saying that the BRUPT register should work just fine.  But then I see that on the website it explicitly says it used to and doesn't any longer.  I understand the argument it gives, but don't see why I would have removed the feature.  I guess it must have some unpleasant side effect, and I must have rationalized that it was okay to remove it rather than fix it.  I don't suppose I would have done so without first checking that it never ever happened in Luminary 131 or Colossus 249, but obviously that says nothing at all about all these other AGC versions we have now.  Alas!

Rather than the random million monkey test I described above, I considered saying that somebody should write up a test of every boundary condition of every instruction (which is perhaps where you were going with the Aurora observation), which I think is better in some ways and not better in others than the million-monkey test, but definitely seems more grueling and error-prone to create.  :smile:  I think it's what I set out to do with Validation, and then quickly ran out of steam.

**Comment by thewonderidiot** [comment]
Yeah, the reason it was on the top of my mind is I remember Niklas pointing out at one point that they had re-enabled BRUPT in the NASSP copy of agc_engine.c. Apparently it is used in some versions of the Luminary autopilot. It's been on my todo list to try to figure out why it had been disabled, and fix whatever issue it was causing... I just haven't gotten around to it.

Also, I wasn't pitching those as either-or. 😉 While the fuzzing test is certainly better in some ways, there are features of computer that haven't been exercised so far that I'd like to before pressing print on a bunch of expensive PCBs. The new test route is the only way to go there, and some of the tests I want to run would be _so much easier_  if I had the waitlist and more complex human interaction than Validation. :smile:

And it's a lot less grueling, I think, since we have so many tests written by Ed Smally now.

Speaking of Smally tests, and things that aren't exercised by Aurora or Retread... one thing I've been wondering throughout all of this is, where the heck was EDRUPT used?! Supposedly it was included for Smally's system test programs, but neither Aurora nor Retread has a single instance of it. I was really thinking we were going to see it in the Retread instruction test.... My only theory, now that most of the programs I would have expected to see it in have surfaced, is that perhaps it was usually injected by the Monitor or some other ground equipment.

**Comment by thewonderidiot** [comment]
I've verified that the fixes for the DCA and I/O+overflow tests above resolve all failures on the hardware sim as well. That's it for the Retread tests! :smile:

**Comment by thewonderidiot** [comment]
@rburkey2005, I put together the skeleton for what I was talking about in a new program folder called "Borealis". In it, I've successfully managed to scrub all DAP-related stuff from Aurora 12 (the string "DAP" doesn't appear anywhere now, I think). It's possible I may have gone too far in places... but none of the functionality I removed was specified in that document describing Aurora's capabilities, so meh, no harm done. It assembles without any errors and appears to behave correctly, to the limited extend that I've interacted with it. At the very least, the self-test still runs fine.

I need to decide how I want to handle bringing in the various tests... I might keep them logically separate and assign different nouns to the different groups. So N21 would be Aurora tests, Nxx would be Retread tests, etc.
