### ISSUE TITLE
Correct comment text errors in the completed transcription

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#736]
This is kind of hopeful... Luminary 116 is printed incredibly faintly, and it was a chore coming up with octopus parameters for the octals. And unfortunately, unlike the octals, much of the code is on paper with thin dark lines that will make it harder.

In an attempt to mitigate the issue, I've created the skeleton for Luminary 116 out of Luminary 99, even though it's structurally and temporally closer to Luminary 131. The former, however, has gone all the way through comment text corrections, whereas the latter is still pending better scans or multi-way diffing.

**Comment by rburkey2005** [comment]
Alas!  Why did I not snag Don's copy of Luminary 131 much sooner?  Then I might have been able to fix up the Luminary 131 transcription before this ever became an issue.  Well ... next time (the next life, perhaps?) I'll know better!

**Comment by rburkey2005** [comment]
I've decided to go ahead and sponsor the Luminary 131 scan myself, and I sent Don the paperwork for it, implying that if he wanted to take it to archive.org along with the next batch of two docs, rather than putting it at the very end of the scanning queue, it would be okay.  Probably it's too late to make any difference for the work on Luminary 116, but I took a shot anyway.  I doubt it will delay any of the other scans, since the bottleneck seems to be Don's delivery of the printouts, rather than archive.org's scanning of them.  Besides, it would definitely be better to have Luminary 131 fully corrected (or as fully as the methods I'm using allow) _before_ transcribing Zerlina, so we don't have this same problem all over again.

**Comment by rburkey2005** [comment]
And indeed, Don says he'll do that ... that he was intending to take the next batch to archive.org (if I recall rightly, two digital sims) this afternoon, and that he'll add Luminary 131 to that.  So we'll see what happens.

**Comment by thewonderidiot** [comment]
I don't think it'll be too much of a big deal for this one -- it's only 17 revisions away vs. 15 revisions away. And I said "structurally" because, like 131, the LAMBERT AIMPOINT GUIDANCE and STABLE ORBIT sections are gone; there aren't any new sections that are only present in 131. Buuut, there's a good chance the 131 scans will show up before we're done here, so if there end up being any major changes we can probably replace the starting file. 😄 

Anyways, sounds like a good plan for Zerlina! I keep forgetting that it branched off at 145. It'll be interesting to see what's in 210 that's not in Zerlina.

**Comment by rburkey2005** [comment]
Because of the relatively-poor printing job, I didn't try an octopus/ProoferComments based proofing.  Instead, I did a 3-way diff vs Luminary 99 and 131 which, since we were starting with a pretty good version anyway, seemed like a fair compromise.  Later, there was a 5-way diff between Luminary 69/99/115/131/210 to route out some additional errors.  (This was followed by a 4-way diff of Colossus 237 & 249, Commanche 55, Artemis 72, and a final cross-diff of Luminary 99 and Comanche 55.  All of these diffs were done in such a way that every correction found was checked could potentially propagate into other AGC versions, and additional Luminary 116 errors may or may not have been found at that point.)  So at least, I now have a pretty good confidence in the consistency of the versions from one to another, and many of these versions had already been proofed with octopus/ProoferCommments.  So in other words, it's checked!  But it might still be worth proofing directly with octopus/ProoferComments ... some day.
