### ISSUE TITLE
Proposal: Add parity bit checking to yaAGC

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#756]
Francois Rautenbach has pointed out that all unused memory locations, not just unused banks, are totally unwired in the core ropes, and attempting to access them will return all 0's with parity error, causing the AGC to reset. We currently simulate such parity alarm resets for nonexistent superbanks, but not for words that are addressable but don't contain anything. But since it's trivial to write a program that does this, and with the right DSKY inputs and astronaut can make it happen, I'd like to propose that we start simulating this. Additionally, I think (but need to check) that SUPER JOB utilizes this behavior in its fault handling demonstrations.

The proposal is to do the following:
1. Make --hardware the default in yaYUL.
2. Tweak yaYUL to only generate parity bits for words that are actually used by the program.
3. Add runtime parity bit checking to yaAGC.
4. Modify other tools (oct2bin et al) to produce parity properly.

This downside is that this creates a binary incompatibility with previous versions. Rather than cutting over entirely, if we still want to support old binaries, we can try to make yaAGC support both. Unfortunately, the current ROM file format doesn't have any sort of header where we can specify a revision; it's just raw data. There are a couple of possible options without adding a header or footer or something like that:
1. Change the file extension and go based on that.
2. Do it heuristically. When loading the rom, scan the first N words (maybe even the whole thing) checking the parity bit position for a 1. If any 1s are found, then parity checking is enabled.

**Comment by thewonderidiot** [comment]
I've gone ahead and done *#*2 from the list above for --hardware; parity bits are now only added to words that are actually used.

**Comment by rburkey2005** [comment]
My initial reaction to this is not positive. I don't see a compelling reason for this rather sweeping change. Leaving parity out of the software sim was a design decision and not an oversight. In Hugh's words, when I discussed this very issue with him (in connection with the block 1 sim)  "parity schmarity!" Is the sole motivation for this the desire to run SuperJob?  Francois's observation, while interesting, isn't a compelling motivation, because the contents of unallocated memory are never accessed in any way, so no parity error can ever be detected. If it's just for SuperJob, implement it in the minimal possible way, and certainly not as the default, where it affects every tool and a dozen existing AGC code bases.

**Comment by rburkey2005** [comment]
Okay, it's too close to my sleepy time. Upon re-reading this and thinking about it some more, my only real objection is to changing the default. I think the default should be what it is now, but I don't have any objection to the heuristic implementation of parity checking, which seems to me to be transparent, and the optional generation of parity for SuperJob. But not for everything else, and not as a default.

**Comment by rburkey2005** [comment]
With the block 1 sim, there were all kinds of edge cases where the parity bit ended up leaking into the 16-bit central registers. It was too hard tracking down all those cases, so I ended up just disabling parity entirely. Very bad memory for me. So if yaYUL checks parity, that's fine, but I'd like the parity stored separately from the 15 bit data within yaUL, and not in the 16th data bit.

**Comment by thewonderidiot** [comment]
Well, SuperJob and any other test programs we would find in an ideal world (Artemis, Newspeak, Twospeak, Lamesh, etc.). I'm probably going to make Borealis do this now, as well.

My angle for this (and most other things) was to strive for accuracy wherever possible. It's true that the flight ropes never do this themselves, but all it would take is, say, a V01N01E 5777E to crash Luminary 210. Admittedly, this is extremely contrived. But I do understand the desire to not change a bunch of stuff for a corner case.

Anyways, I'll split out the parity bits in yaYUL as requested and take a shot at the heuristic implementation for yaAGC, then make a pull request if it works. I'm warming up to that approach myself; there's no change at all for anybody, unless they go out of their way to assemble a rom with --hardware, and then it will "just work" for them.

**Comment by thewonderidiot** [comment]
Okay, I separated parity bits and data words in yaYUL. Would you like them to be stored separately within yaAGC as well?

**Comment by thewonderidiot** [comment]
I assumed the answer to that was going to be a 'yes' and took a shot at implementing the heuristic approach. The pull request is up at #757. 😄

**Comment by rburkey2005** [comment]
@thewonderidiot I meant the parity should be separated in yaAGC, sorry; there's no reason at all to separate the parity bits in yaYUL. For whatever reason, the notification for this issue took 7 hours to reach my phone, when I literally couldn't keep my eyes open, so that's my excuse for writing up such a negative and inaccurate set of comments. But you seemed to be moving so quickly that I felt I had to register my thoughts immediately, for fear I'd wake up and find that everything had changed overnight.  :smile:  Now that I'm awake again, let me give my variation of your proposal that I _would_ support, though it overlaps somewhat with what you've already said.  As you've perceived, the underlying principle is to not introduce any binary incompatibilities for existing AGC programs.  Even so, some difficulties remain.

1. Make --hardware the default in yaYUL?  No!  My recollection (forgive me if I'm wrong) is that --hardware reorders banks 00-03.  I don't like that at all.  I would certainly be happy with a --parity switch instead that merely generated parity bits.  But not as the default.
2. Tweak yaYUL to only generate parity bits for words that are actually used by the program?  Fine, obviously, though I assume you also mean it should generated incorrect parity bits for words that are _not_ actually used by the program.
3. Add runtime parity bit checking to yaAGC?  Fine, but I like the "heuristic" approach best and, as I said and as you've done, only when the parity bits are stored separately in memory from the data bits, which would retain a 16th bit of zero to avoid unexpected side effects.  I assume you don't mean _full_ parity-bit checking, but only parity checking for fixed memory.  Erasable memory also has parity, which is not only inspected at runtime but is also generated at runtime as well, and that seems to me to be a much bigger hassle.
4. Modify other tools (oct2bin et al) to produce parity properly?  Fine, but only with a command-line switch (say, --parity).  The output 16th bit should remain 0 by default.

But item 4 seems to me to be an irritating road-block.

For one thing, for oct2bin --parity output to remain compatible with yaYUL --parity output as described above, the existing binsource files have to be edited to allow some scheme for marking Francois's unused words, say with an '@'.  That seems like a big hassle.  It could probably be automated for most AGC versions, but for Solarium and Retread, there are unused holes right in the middle of the banks, so they would have to be edited manually.  

Plus, tracking down and modifying the various tools that are based on the current design assumptions could turn out to be a bigger hassle than you may assume, since some are seldom-used and aren't referenced by Makefiles, so they're hard to identify.  An example that comes to mind is the tool that interconverts between Virtual AGC octals and Julian Webb's octals.  While it's true that Julian has closed-source his AGC simulator into complete obscurity and has failed to even answer his emails for years, that doesn't mean I care to abandon the ability to do the interconversion.   Other tools are probably of a similar level of obscurity, so that you (I mean I) never even recall that they exist until they're actually needed.  Perhaps they'll work as-is, perhaps not, but you have to identify them first and think them through to know.

**Comment by thewonderidiot** [comment]
Ahh, no worries. I opened this issue so we could talk about it -- I'd rather not make such a big change without buy-in. 😄 I just went ahead with the correction to --hardware since I still think I'm the only one that uses it.

I'm totally on board with a minimalist approach to this. After thinking about it some, I'm fine with dropping --hardware in favor of --parity in yaYUL. I can just swizzle the banks in my own tools when I go to program things. I'm also fine with updating all of the binsource files myself.

For all of the other tools, it seems like the best approach to me (and this might be what you're getting at) would be to simply mask out the parity bit and let them go about their business as they did before.

As far as erasable parity is concerned -- I would only be pushing for that one if I could come up with a way to do anything with it. I'm fairly certain that all of the words were written to with correct parity during erasable memory module bringup, and then retained that correctness more or less for the rest of forever. I think the _only_ way to end up with bad erasable parity is to interrupt power to the AGC in the middle of an erasable memory cycle, after the word in question has been read but before it has been written back out. Unlike the fixed parity alarm, which you can hit with one verb/noun on the DSKY or trivially in a program, that's not really something you can do without the help of an EGSE system that knows how to turn off the computer at _just_ the right moment. That sort of thing is definitely beyond the scope here. (Interesting sidenote: Apollo 13's explosion did cause exactly this sort of power interruption, so there's a small chance that they might have gotten a single word with bad parity).

**Comment by rburkey2005** [comment]
@thewonderidiot You already made the change to --hardware, which is perfectly fine for the reasons you mentioned, so I don't see why any additional "swizzling" should be needed just because --parity duplicated some of that functionality.

**Comment by thewonderidiot** [comment]
Okay, that works for me.
