### ISSUE TITLE
Sunburst37.binsource not consistent with octal listing

### ISSUE THREAD

**Issue by 7ofNine** [virtualagc/virtualagc#940]
The binsource file contains in line 549 (BANK=1) 
477371	511430	711321	677370	511430	551321	342631	543461	
while the corresponding octal listing p.1118 shows
![image](https://user-images.githubusercontent.com/12020184/27185946-e1eebc38-51b4-11e7-8168-2d8fb11849f9.png)
i.e. 34265 vs. 34263 this also is shown in the source listing p. 82
![image](https://user-images.githubusercontent.com/12020184/27186164-7a987686-51b5-11e7-8913-b39ce404f1ea.png)

**Comment by rburkey2005** [comment]
@7ofNine Cool!  I'll check into it.

**Comment by rburkey2005** [comment]
@7ofNine @thewonderidiot  I love this error!  

Normally, with most simple checksumming schemes, single-word errors would _always_ create a bad checksum ... in other words, if there's a correct checksum but a binary error, there would have to be _at least two_ binary errors.  But the checksumming used in the AGC is no normal scheme, and in this case a single-digit error in a single octal word nevertheless produced a correct checksum and was therefore undetectable.  That's because both the bank number and the negative of the bank number are valid checksums.  In this case, the bank number is 1, so the checksum could be either 1 or -1, and thus an off-by-two error could possibly (but not necessarily) flip the checksum from 1 to -1 or vice-versa.  And of course, 34265 and 34263 do indeed differ by 2.  Lovely!

And of course, the parity is the same, so the error couldn't be detected that way.  And '3' looks reasonably similar to '5', so the error is less detectable with tools like ProoferBox.py than a lot of other types of errors.  And so on.  :smile:

At any rate, I fixed it.  I hope.  Thanks!

**Comment by thewonderidiot** [comment]
Hahaha, woooow. That's an incredible error. Nice catch! :smile:
